### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [MonikaChloe/prj-rev-bwfs-dasmoto#3]
Met expectations.  You match the site to the spec visually.

So in this first project I look for two items.

First did you use divs to organize each section.  The goal is to get you into the habit of using divs now instead of figuring it out later.  In the later projects you will be building your sites with divs and using flexbox.

Second item I look for is repetition in css.  In the later projects your css file will be 100s of lines.  The less you type the less likely you are to make a mistake.  Also if you make a mistake, it is faster find since you have less lines of code.  Efficiency is important so I emphasize this now.

As a challenge go to flexboxfroggy.com see how far you can get. In the later projects you will be using flexbox heavily.  This will prepare you for them.

**Comment by MonikaChloe** [comment]
Thank you for your feedback - will defiantly be implementing the 2 points you have pointed out. Thanks again!
